/**
 * Regenerate the BENCHMARKS.md benchmark tables. Two modes, matching the two
 * refresh cadences (see CLAUDE.md):
 *
 *   node --expose-gc --import tsx bench/report.ts self
 *     Benchmarks ONLY this repo's own parser (group "ours") + JSON baseline, and
 *     rewrites the "Our implementation" block. Fast. Run before every commit/PR.
 *     If no lightning-yaml parser exists yet, writes a caveat and exits — nothing
 *     to benchmark.
 *
 *   node --expose-gc --import tsx bench/report.ts competition
 *     Benchmarks the competition (JSON + js-yaml + yaml) across the full matrix
 *     and rewrites the "Competition" block. Slow (xlarge/yaml). Run only when
 *     dependency versions or datasets change.
 */

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { candidatesInGroup, candidateSupports, type Scope } from "./candidates.ts";
import { runMemoryMatrix, formatMarkdown } from "./memory/run.ts";

const BENCHMARKS = fileURLToPath(new URL("../BENCHMARKS.md", import.meta.url));

function speedPath(script: string): string {
  return fileURLToPath(new URL(`./speed/${script}`, import.meta.url));
}

/** Run a mitata speed script in markdown mode and return its stdout. */
function runSpeed(script: string, scope: Scope): string {
  const p = spawnSync(
    process.execPath,
    ["--expose-gc", "--import", "tsx", speedPath(script)],
    {
      encoding: "utf8",
      maxBuffer: 64 * 1024 * 1024,
      env: { ...process.env, BENCH_FORMAT: "markdown", BENCH_SCOPE: scope, FORCE_COLOR: "0" },
    },
  );
  if (p.status !== 0) throw new Error(`${script} failed:\n${p.stderr}`);
  return p.stdout.trim();
}

/** Separate mitata's "clk/cpu/runtime" header lines from the table body. */
function splitMitata(md: string): { header: string[]; body: string } {
  const isHeader = (l: string) => /^(clk|cpu|runtime):/.test(l);
  const lines = md.split("\n");
  return {
    header: lines.filter(isHeader),
    body: lines.filter((l) => !isHeader(l)).join("\n").trim(),
  };
}

/** Build the full markdown block for a scope by running speed + memory. */
async function buildBlock(scope: Scope, generatedBy: string): Promise<string> {
  const parse = splitMitata(runSpeed("parse.bench.ts", scope));
  const stringify = splitMitata(runSpeed("stringify.bench.ts", scope));
  const memory = runMemoryMatrix({ scope });

  const env = parse.header.length ? parse.header : stringify.header;

  return [
    `_Generated by \`${generatedBy}\`. Representative snapshot — timings drift run-to-run; peak-RSS/heap-Δ are the stable figures._`,
    "",
    "```",
    ...env,
    "```",
    "",
    "### Speed — parse (mitata, sequential)",
    "",
    parse.body,
    "",
    "### Speed — stringify (mitata, sequential)",
    "",
    stringify.body,
    "",
    "### Peak memory (isolated processes, sequential)",
    "",
    formatMarkdown(memory).trim(),
  ].join("\n");
}

function inject(doc: string, marker: string, content: string): string {
  const start = `<!-- BENCH:${marker}:START -->`;
  const end = `<!-- BENCH:${marker}:END -->`;
  const si = doc.indexOf(start);
  const ei = doc.indexOf(end);
  if (si === -1 || ei === -1) {
    throw new Error(`BENCHMARKS.md is missing the ${start} … ${end} markers`);
  }
  return doc.slice(0, si + start.length) + "\n" + content + "\n" + doc.slice(ei);
}

async function main(): Promise<void> {
  const mode = process.argv[2];
  let doc = readFileSync(BENCHMARKS, "utf8");

  if (mode === "competition") {
    console.log("Benchmarking all parsers (JSON + js-yaml + yaml + lightning-yaml), full matrix…");
    // Scope "all" makes this a genuine head-to-head: our parser sits in the same
    // tables as the competition. The per-fixture capability probe still drops
    // lightning-yaml from fixtures it can't read yet (e.g. yaml-rich anchors),
    // so those rows honestly show only the parsers that handle them.
    const block = await buildBlock("all", "pnpm bench:competition");
    doc = inject(doc, "COMPETITION", block);
  } else if (mode === "self") {
    const ours = candidatesInGroup("ours");
    const ready = ours.filter((c) => candidateSupports(c, "parse") || candidateSupports(c, "stringify"));
    if (ready.length === 0) {
      console.log("lightning-yaml is still a stub (parse/stringify throw) — writing caveat, nothing to benchmark.");
      const block =
        "_`lightning-yaml` is registered as a candidate but its `parse`/`stringify` " +
        "are not implemented yet (they throw `NotImplementedError`), so there is nothing " +
        "to benchmark here._\n\n" +
        "_This block refreshes automatically once `src/index.ts` implements them; until " +
        "then, `pnpm test` runs the consistency suite that specifies what \"correct\" means._";
      doc = inject(doc, "OURS", block);
    } else {
      console.log(`Benchmarking our implementation (${ready.map((c) => c.name).join(", ")}) + JSON baseline…`);
      const block = await buildBlock("ours", "pnpm bench:self");
      doc = inject(doc, "OURS", block);
    }
  } else {
    console.error("Usage: report.ts <self|competition>");
    process.exit(1);
  }

  writeFileSync(BENCHMARKS, doc);
  console.log(`Updated ${BENCHMARKS}`);
}

await main();
